### ISSUE TITLE
Feature: Autocomplete

### ISSUE THREAD

**Issue by Tolfx** [saas-js/saas-ui#154]
# Feature Request
Really like the solutions this provides but would love for the autoform / or new form of a autocomplete like MUI, having a select and trying to find over the hundreds of items like finding a currency would be great to have some sort of "search" or "autocomplete", would be also great to have extra functionality. Usually want to search for a customer but if I fail to find one would be great if the component sends a event "failedSearch" in some sort of kind to so I can fetch manually of to project the state of if something got found.

**Comment by Pagebakers** [comment]
Thanks for your feedback @Tolfx , the reason why it's not added yet is because it's on the Chakra UI roadmap (combobox) and Saas UI Pro has an MenuInput component that allows you to add a search input to a menu dropdown.

You can integrate with React Select
https://github.com/csandman/chakra-react-select

Here's also a custom example with Ark Combobox
https://github.com/saas-js/chakra-ui-combobox

You can make them work with Autoform using `createField`
https://saas-ui.dev/docs/components/forms/form#defining-custom-form-fields

**Comment by Pagebakers** [comment]
Will add this to the public roadmap.

have you tried any of the suggested solutions?

**Comment by Tolfx** [comment]
Hi, yes I tried using [chakra-react-select](https://github.com/csandman/chakra-react-select) then used createField to add it, worked well but experienced issues in general with forms so couldn't use it either way.

Thanks for the help either way.

**Comment by lsarni** [comment]
Hi, we would also like this feature.
