### ISSUE TITLE
Props passed to modals managed by the Modals Provider are not reactive

### ISSUE THREAD

**Issue by kculmback-eig** [saas-js/saas-ui#68]
We are trying to use the modals manager but are running into an issue where props passed to the body, footer, etc are not reactive. 

Here is a somewhat contrived example of the issue:
https://codesandbox.io/s/serene-yalow-dygp0y?file=/src/index.tsx

The `isLoading` prop is not reacting to the state change of the mutation from react-query. 

Is there a good way to pass reactive props to these components?

**Comment by Pagebakers** [comment]
Thanks for opening this issue.

The properties passed to modals.open, drawer, etc aren't reactive at the moment. This is because each instance is stored in a regular Set instance.

```ts
  // Note that updating the Set doesn't trigger a re-render,
  // use in conjuction with setActiveModal
  const _instances = React.useMemo(() => new Set<ModalConfig>(), [])
```

We could use something like useSet (https://react-hookz.github.io/web/?path=/docs/state-useset--example) here to make it reactive. I recon it won't affect performance much, since there usually will be maximum 1 or 2 modals open.

Until then I recommend doing this:

https://codesandbox.io/s/exciting-johnson-15yydy?file=/src/index.tsx

Create a separate Drawer component and then simply use `modals.open(MyDrawer)`

**Comment by kculmback-eig** [comment]
Thanks, @Pagebakers !

We will use `modals.open(MyDrawer)` for now. Would you like me to leave this issue open or go ahead and close it?

**Comment by Pagebakers** [comment]
Not going to implement this for now. If you need reactivity in the modal it's better to create a separate component and open this.
