### ISSUE TITLE
Stepper won't allow select dropdown for non saas-ui elements

### ISSUE THREAD

**Issue by ryanapfel** [saas-js/saas-ui#89]
Using react-select, you cannot see the select dropdown when the select is within a Stepper component.

**Comment by Pagebakers** [comment]
Thanks for reporting this.

Could you create a reproduction for this? https://stackblitz.com/
Then I can see if there is a work around for it.

**Comment by ryanapfel** [comment]
Sure thing! See below. It looks like if you increase the padding/area around the selector, it will show the select options. A little sub-optimal if the select is at the bottom of the stepper component though. 

[Stackblitz](https://stackblitz.com/edit/react-eyvtia?file=src/App.js)
Thanks for looking into this!

**Comment by Pagebakers** [comment]
Great, thanks for taking the time for setting up the example.

The culprit is this:
<img width="731" alt="Screenshot 2022-09-25 at 21 18 32" src="https://user-images.githubusercontent.com/32583/192161373-af1d12e4-9dad-4719-943b-027d710b1715.png">

It shouldn't have overflow:hidden when it's not collapsed. I will look into a fix.

Other solution for now is to use a portal for the select. You can use the menuPortalTarget property for this.
https://react-select.com/advanced#portaling

This will allow the select dropdown to be rendered outside of the overflow:hidden div.

**Comment by ryanapfel** [comment]
Thank you!
